apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentinel-ingress
  namespace: sentinel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sentinel-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentinel-web
                port:
                  number: 80
